export const metatype = {
    class: "system",
    variant: "type",
    type: "system.type",
    label: "System root type",
    version: 0,
    generation: 1,
    relations: {},
    read_permission: "",
    mutate_permissions: [],
    counts: [],
    commits: {
        created_by: "henrik",
        created_time: {
            nanoseconds: 630000000,
            seconds: 1702416553,
        },
        updated_by: "henrik",
        updated_time: {
            nanoseconds: 859000000,
            seconds: 1702416615,
        },
    },
    properties: {
        defaults:{
            system:{
                class: "system",
                variant: "type",
                type: "system.type",
                label: "System root type",
                version: 0,
                generation: 1,
                relations: {},
                list_permission_group: "",
                permissions: [],
                counts: [],
                commits: {
                    created_by: "henrik",
                    created_time: {
                        nanoseconds: 630000000,
                        seconds: 1702416553,
                    },
                    updated_by: "henrik",
                    updated_time: {
                        nanoseconds: 859000000,
                        seconds: 1702416615,
                    },
                },
            },
            properties:{
                fields:[],
                views:{},
                settings:{},
            }
        },
        metadata: {
            views:{
                xs:{
                    component:"string",
                    props:{},
                    children:{},
                    filter: "string",
                },
                sm:{},
                md:{},
                lg:{},
                xl:{},
                edit:{},
            },
            settings:{

            },
            transitions:[],
            structure:{
                component:"string",
                props:{},
                children:{},
            },
            system:{
                type: "array",
                array_type: "map",
                map_type: {
                    database:{
                        type: "string",
                        value: "string",
                        name:"string",
                        ingress:"namespace"
                    },
                    model:{
                        order:"number",
                        type: "string",
                        value: "string",
                        name:"string",
                        ingress:"namespace"
                    },
                    display:{
                        ingress:"namespace",
                        views:{
                            xs:{
                                component:"string",
                                props:{},
                                children:{},
                                filter: "string",
                            },
                            sm:{},
                            md:{},
                            lg:{},
                            xl:{},
                        },
                    },
                    mutate: {
                        component:"RC",
                        ingress:"namespace",
                        props:{},
                        children:{},
                        error_message: "string",
                        help_message:"string",
                        min: "number",
                        max: "number",
                        minlength: "number",
                        maxlength: "number",
                        readonly: "boolean",
                        required: "boolean",
                        spellcheck: "",
                        type: "string",
                        default:{
                            lookup: "namespace",
                            value: "string",
                        },
                        change: "namespace",
                        verify: "namespace",
                        report: "namespace",
                        filter: "string",
                        placeholder: "",
                        name: "string",
                        order: "number",
                        size: "number",
                    },
                },
            },
            properties:{
                type: "array",
                array_type: "map",
                map_type: {
                    database: {
                        name: "string",
                        type: "string",
                        value: "string | object",
                        ingress:"namespace",
                    },
                    model:{
                        order:"number",
                        required:"boolean",
                        property:"string",
                        type: "string",
                        value: "string",
                        label: "string",
                    },
                    mutate: {
                        error_message: "string",
                        help_message:"string",
                        min: "number",
                        max: "number",
                        minlength: "number",
                        maxlength: "number",
                        readonly: "boolean",
                        required: "boolean",
                        spellcheck: "",
                        type: "string",
                        default:{
                            lookup: "namespace",
                            value: "string",
                        },
                        change: "namespace",
                        verify: "namespace",
                        filter: "string",
                        format: "string",
                        placeholder: "",
                        name: "string",
                        order: "number",
                        size: "number",
                    },
                    display: {
                        views:{
                            xs:{},
                            sm:{},
                            md:{},
                            lg:{},
                            xl:{},
                        },
                    },
                },
            },
        },
    },
}
